# Remember to update JTFRAME_SKIP when adding
# or removing betas
ngpc:   [ mister, pocket ]
xmen:   [ mister, pocket ]
s18:    [ mister, pocket ]
riders: [ mister, pocket ]
wc:     [ mister, pocket ]
flstory: [ mister, pocket ]
