[parse]
sourcefile=[ "twin16.cpp" ]
parents= [
    {name="mia",description="Missing in Action"},
    {name="cuebrick",description="Cuebrick"}
]
skip = { machines=[
    "fround",
] }
debug = { machines=["devilw", "vulcan", "cuebrick", "mia"] }

[buttons]
names=[
    { machine="devilw", names="Power up,Shoot,Jump" },
    { machine="vulcan", names="Special power,Shoot,Missile" },
    { machine="mia",  names="Knife, Weapon, Weapon select" },
]

[dipsw]
delete=[{names=["Unused","Unknown"]}]

[ROM]
# values starting with $ refer to macro definitions in the .def file
# or arguments passed to mame2mra
regions = [
    { name="maincpu", width=16, reverse=true  },
    # bank 1
    { name="sub",     width=16, reverse=true, start="JTFRAME_BA1_START"  },
    { name="data"  },
    { name="gfxrom",   start="GFX_START", width=32 },
    { name="gfxrom",   skip=true, setname="cuebrickj" },
    # bank 2
    { name="audiocpu", start="JTFRAME_BA2_START" },
    { name="k007232",  start="PCM_START"  },
    { name="upd",      start="UPD_START"  },
    # bank 3
    { name="fixed",    start="JTFRAME_BA3_START"   },
]

order = [
    "maincpu", "sub", "data", "gfxrom",
    "audiocpu", "k007232", "upd", "fixed"
]

patches = [
    # skip ROM check
    { setname="fround", offset=0x1058, data="12 11" }
]