[parse]
sourcefile=[ "gaiden.cpp" ]
skip = { setname="mastninj", machines=[
	"drgnbowl", # encrtyped CPU
	"stratof", # uses MCU
] }

debug = { machines=["drgnbowl", "raiga" ] }

[dipsw]
delete=[
	{names=["Unused","Unknown"]},
	{names=["Flip Screen"]}, # not fully implemented
]
rename=[
	{name="Difficulty (Wild Fang)",    to="Difficulty"},
	{name="Difficulty (Tecmo Knight)", to="Difficulty"},
]

[header]
info="""byte 0: 0 = no frame buffer for sprites
                     1 =    frame buffer enabled
                    0? = obj data delayed 10 pixels
                    1? =                  11 pixels"""
data=[
	{machine="shadoww", offset=0,data="02"},
	{machine="wildfang",offset=0,data="01"},
]

[buttons]
names=[
    { machine="shadoww",  names="Grab,Attack,Jump"  },
    { machine="wildfang", names="Jump,Punch,Change" },
]

[ROM]
regions = [
	{ name="maincpu", width=16, reverse=true },
	{ name="audiocpu", start="JTFRAME_BA1_START" },
	{ name="oki", start="PCM_START" },
	{ name="mcu", skip=true, machine="wildfang" },
	{ name="gfx1", start="JTFRAME_BA2_START", reverse=true },
	{ name="gfx4", start="OBJ_START", width=16, reverse=true }, # objects
	{ name="gfx2", start="JTFRAME_BA3_START", reverse=true }, # background
	{ name="gfx3", start="GFX3_START", reverse=true },        # foreground
]

order = [ "maincpu", "audiocpu", "oki",
	"gfx1","gfx4","gfx2", "gfx3" ]
