[global]
author=["jotego"]

[buttons]
names=[
	{ machine="flstory", names="Shot,Jump" }
]

[parse]
sourcefile=[ "flstory.cpp" ]
debug={ machines=[
	"onna34ro",
	"victnine",
	"rumba",
]}

[dipsw]
rename=[
	{ name="Attract Sound on Title Screen",to="Attract Sound" },
	{ name="Copyright String",to="Maker" },
]
# delete=[
# 	{ names=["Unused"] },
# ]

[header]
info="""

		byte 0: PCB id
		byte 1: 0 == same orientation as flstory
		        1 == flipped both XY
		        2 =  flipped only Y - to be tested -
		byte 2: 0 == MCU enabled
		        1 == MCU disabled
"""
fill=0
PCBs = [
	{ machine ="flstory"  },
	{ machine ="onna34ro" },
	{ machine ="victnine" },
	{ machine ="rumba"    },
]
data = [
	{ pcb_id=true, offset=0 },
	{ machines=["onna34ro","victnine"], data="01", offset=1 },
	{ machines=["rumba"],               data="02", offset=1 },
	# Disable MCU
	{ setname="onna34roa",              data="01", offset=2 },
]

[ROM]
regions = [
	{ name="maincpu"                             },
	{ name="audiocpu", start="JTFRAME_BA1_START" },
	{ name="gfx1",     start="JTFRAME_BA2_START", width=16, sequence=[0,4,1,5,2,6,3,7] },
	{ name="bmcu:mcu", start="JTFRAME_PROM_START"},
]

order=["maincpu","audiocpu","gfx1","bmcu:mcu"]